name: Always Succeed Workflow

on: [push, pull_request]

jobs:
  success_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Always Succeed Step
        run: |
          echo "This step always succeeds!"
          exit 0
